# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91ed2e148f2f7fdba6c5f44142dd35a033fee64945a25175259b9c61d5bc5c293c9e934414e0be38013cbb20797dcd5742d46bc33410d420714e34a6d7387f17

test:
  secret_key_base: 9dcddbf5c56e0f979e7dc7f159980a2e3f640c8553d20814dc3eb686aae4749fdc08a3c7961884cbb598ea9e8575d683d166591ba35dd968413c161d1ef180ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
